name: markdown-ci

on:
  push:
    paths:
      - "task.md"

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run markdown workflow
        run: python runner.py task.md